-- =====================================================
-- Demo 01: Setup database, schema, warehouse, roles
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- Roles
CREATE ROLE IF NOT EXISTS DEMO_STREAMLIT_ADMIN;
CREATE ROLE IF NOT EXISTS DEMO_STREAMLIT_USER;
GRANT ROLE DEMO_STREAMLIT_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE DEMO_STREAMLIT_USER  TO ROLE DEMO_STREAMLIT_ADMIN;

-- Cortex AI permissions (for future Cortex features in app)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_STREAMLIT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEMO_STREAMLIT_USER;

-- Git repository access
GRANT USAGE ON DATABASE       SNOWFLAKE_QUICKSTART_REPOS                           TO ROLE DEMO_STREAMLIT_ADMIN;
GRANT USAGE ON SCHEMA         SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS                 TO ROLE DEMO_STREAMLIT_ADMIN;
GRANT READ  ON GIT REPOSITORY SNOWFLAKE_QUICKSTART_REPOS.GIT_REPOS.DEMOS_REPO      TO ROLE DEMO_STREAMLIT_ADMIN;

-- Warehouse
CREATE OR REPLACE WAREHOUSE DEMO_STREAMLIT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'Snowflake Streamlit demo warehouse';

GRANT USAGE ON WAREHOUSE DEMO_STREAMLIT_WH TO ROLE DEMO_STREAMLIT_ADMIN;
GRANT USAGE ON WAREHOUSE DEMO_STREAMLIT_WH TO ROLE DEMO_STREAMLIT_USER;

USE WAREHOUSE DEMO_STREAMLIT_WH;

-- Database
CREATE OR REPLACE DATABASE DEMO_STREAMLIT_DB
    COMMENT = 'Streamlit demo DB';

GRANT OWNERSHIP ON DATABASE DEMO_STREAMLIT_DB
    TO ROLE DEMO_STREAMLIT_ADMIN COPY CURRENT GRANTS;

USE ROLE DEMO_STREAMLIT_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_STREAMLIT_DB.ANALYTICS;

USE ROLE ACCOUNTADMIN;
GRANT USAGE  ON DATABASE DEMO_STREAMLIT_DB                                    TO ROLE DEMO_STREAMLIT_USER;
GRANT USAGE  ON SCHEMA   DEMO_STREAMLIT_DB.ANALYTICS                          TO ROLE DEMO_STREAMLIT_USER;
GRANT SELECT ON ALL TABLES    IN SCHEMA DEMO_STREAMLIT_DB.ANALYTICS TO ROLE DEMO_STREAMLIT_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_STREAMLIT_DB.ANALYTICS TO ROLE DEMO_STREAMLIT_USER;

SELECT '01_setup_db: done' AS status;
